# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

idw <- function(values, dists, p) {
    .Call(`_babyCaret_idw`, values, dists, p)
}

voting <- function(values, dists, levels, p) {
    .Call(`_babyCaret_voting`, values, dists, levels, p)
}

mergeCompanion <- function(vA, vB, bx1, ex1, bx2, ex2) {
    invisible(.Call(`_babyCaret_mergeCompanion`, vA, vB, bx1, ex1, bx2, ex2))
}

mergeSortCompanion <- function(by, with, bx, ex) {
    invisible(.Call(`_babyCaret_mergeSortCompanion`, by, with, bx, ex))
}

insertCompanion <- function(by, with, byCand, withCand) {
    invisible(.Call(`_babyCaret_insertCompanion`, by, with, byCand, withCand))
}

cpp_makeDist <- function(isNum, trainMat, testMat, manhattan, w) {
    .Call(`_babyCaret_cpp_makeDist`, isNum, trainMat, testMat, manhattan, w)
}

cpp_knnPredict <- function(dists, target, k, p, levels) {
    .Call(`_babyCaret_cpp_knnPredict`, dists, target, k, p, levels)
}

cpp_knn <- function(isNumeric, trainMat, testMat, target, manhattan, k, p, featWeights, levels) {
    .Call(`_babyCaret_cpp_knn`, isNumeric, trainMat, testMat, target, manhattan, k, p, featWeights, levels)
}

calculateDist <- function(isNum, dataNums, dataCats, protoNums, protoCats, rows, cols, k, lambda) {
    .Call(`_babyCaret_calculateDist`, isNum, dataNums, dataCats, protoNums, protoCats, rows, cols, k, lambda)
}

